In [1]:
import numpy as np
import pandas as pd
from utils.utils import PROJECT_DATA_DIR
import os
import mxnet as mx
import tarfile

C:\Users\gilbe\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:29:16.151321. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)


In [18]:
data = pd.read_csv(os.path.join(PROJECT_DATA_DIR, 'all_training_200_4.csv'))

C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:38:03.489213. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)


In [19]:
data.head()

98 -10 -66 201 14 -441 -17 133 -476 -165 -11 -192 -35 -100 -525 86 7 -225 -76 50 -85 -35 -79 -359 -116 44 -274 -4 34 -66 115 0 -69 155 51 79 110 9 96 -1 -91 215 22 59 394 125 79 350 19 -6 24 -19 -75 120 12 4 185 75 20 238 33 -46 116 -102 38 -340 -93 30 -201 -42 89 -16 -104 86 -115 -114 -75 -294 -8 -181 -66 29 -147 65 102 -129 215 14 -120 365 0 -62 296 12 -9 104 -88 115 215 -111 135 291 -169 145 139 -208 124 210 -207 186 -160 -233 130 -429 -185 82 -505 -144 -18 -498 -84 44 -448 -74 39 -455 -151 19 -439 -204 41 -210 -222 39 -161 -143 42 17 -61 8 129 -34 -226 285 -9 4 397 -57 18 493 -120 4 473 -112 14 312 -118 52 199 -120 17 42 -124 52 -84 -169 50 -289 -213 73 -467 -201 73 -524 -217 71 -541 -149 65 -595 -148 63 -523 -106 -42 -394 -70 -19 -130 -70 18 102 -30 -14 254 -12 3 512 34 -35 601 10 49 606 4 -7 582 14 42 509 -24 120 393 -100 137 217 -65 -17 -59 15 -23 -260 -12 69 -452 -102 27 -578 -152 -8 -753 -133 111 -613 -172 136 -537 -200 52 -452 -149 85 -231 42 61 -65 15 8 48 69 -63 325 10 -10 613 127 -16 567 37 -59 647 48 12 559 64 61 387 5 65 118 20 -54 107 3 0 58 -14 35 -191 -25 19 -600 -52 64 -611 -75 39 -453 -61 45 -457 -76 19 -466 -38 23 -321 65 36 -51 94 -11 -96 216 -97 217 159 -68 328 171 -49 418 125 -27 490 112 -78 683 177 -2 468 61 23 101 117 -26 -15 -54 -42 393 -17 31 -139 -75 24 -623 -58 18 -513 -90 134 -502 -61 128 -504 -129 115 -611 -39 6 -324 -58 -54 -221 -49 1 -227 -33 -24 38 -101 -5 226 2 62 450 -19 63 446 -18 4 496 -18 11 457 -28 10 486 -26 46 292 7 -53 38 -56 -2 -58 -120 81 -155 -80 106 -362 -82 17 -306 -129 22 -748 -109 110 -606 -124 40 -316 -101 -10 -357 -89 14 -125 -34 33 73 -50 -64 260 -19 -24 332 17 -55 385 -2 11 463 56 -9 413 -29 26 257 14 -15 224 -78 85 -31 -1 97 -142 -64 42 -316 -17 77 -339 6 49 -405 -41 40 -349 -101 37 -409 -89 -32 -390 -65 12 -235 -22 42 -79 -5 35 1 -18 -5 136 18 23 306 -15 57 449 -27 34 500 -17 -54 417 6 -38 310 95 10 262 32 5 46 -52 30 -62 -83 35 -206 -140 87 -251 -99 63 -353 -111 17 -391 -71 35 -385 5 29 -319 -57 17 -115 10 12 -61 -51 -18 71 -35 16 280 -70 2 181 22 11 264 -44 29 390 -38 44 298 -10 1 228 -50 17 23 -2 42 77 -94 76 -138 -88 27 -266 -102 34 -365 -62 90 -471 -30 49 -368 -23 40 -330 -107 69 -277 -86 42 -84 -114 73 -26 69 -22 306 -39 31 308 191 -66 434 141 -117 262 28 -63 298 49 -19 344 -117 22 105 -133 94 184 -107 12 -26 1
0  -16 22 6 -28 -4 -32 -24 -44 -56 -20 40 -54 -21...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:38:09.191355. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)


In [4]:
data.shape

(199403, 1)

C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:29:24.595155. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)


In [12]:
data_iter = mx.io.CSVIter(
    data_csv=os.path.join(PROJECT_DATA_DIR, 'all_test_2000_1.csv'),data_shape=(1,), batch_size=2**9)

C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:34:06.059976. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)


In [13]:
data_iter

C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:34:29.474451. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)


In [15]:
for batch in data_iter:
    print([batch.data, batch.pad])

[[
[[ 2.600e+01]
 [-4.300e+01]
 [-1.300e+01]
 [ 1.500e+01]
 [-2.600e+01]
 [ 3.600e+02]
 [-5.400e+01]
 [ 2.100e+01]
 [ 2.200e+01]
 [-4.200e+01]
 [ 8.200e+01]
 [-1.323e+03]
 [-1.300e+01]
 [ 7.000e+00]
 [ 4.600e+01]
 [ 3.200e+01]
 [-1.600e+01]
 [-9.530e+02]
 [-3.000e+00]
 [ 4.800e+01]
 [-2.100e+01]
 [ 2.640e+02]
 [-1.308e+03]
 [ 2.100e+01]
 [-1.300e+01]
 [ 2.100e+01]
 [ 1.100e+01]
 [ 1.902e+03]
 [-1.700e+01]
 [ 2.270e+02]
 [-5.600e+01]
 [ 3.600e+01]
 [-2.400e+01]
 [-1.700e+01]
 [-1.000e+00]
 [ 2.568e+03]
 [ 3.300e+01]
 [ 1.000e+01]
 [-1.440e+02]
 [-8.000e+00]
 [-5.000e+00]
 [ 6.900e+01]
 [-5.700e+01]
 [-6.000e+01]
 [ 8.000e+00]
 [-9.000e+00]
 [ 1.900e+01]
 [-3.600e+01]
 [-2.051e+03]
 [ 7.540e+02]
 [-1.200e+01]
 [ 3.900e+01]
 [-5.000e+01]
 [ 2.700e+01]
 [ 1.680e+02]
 [-2.303e+03]
 [ 3.000e+00]
 [ 2.228e+03]
 [-1.600e+01]
 [-3.690e+02]
 [-1.000e+01]
 [ 3.160e+02]
 [-2.200e+01]
 [ 1.200e+01]
 [-8.000e+00]
 [ 5.000e+00]
 [-3.000e+01]
 [-9.000e+00]
 [ 2.700e+01]
 [ 6.870e+02]
 [ 1.610e+02]
 [-

[[
[[ 4.600e+01]
 [ 1.500e+01]
 [ 7.000e+00]
 [ 6.300e+01]
 [ 5.900e+01]
 [-1.000e+01]
 [-1.520e+02]
 [ 1.050e+02]
 [ 9.523e+03]
 [ 1.100e+02]
 [ 1.200e+01]
 [-5.200e+01]
 [ 3.020e+02]
 [-1.000e+01]
 [-1.900e+01]
 [-6.000e+00]
 [-2.010e+02]
 [ 5.780e+02]
 [-1.160e+02]
 [ 7.000e+01]
 [-2.307e+03]
 [ 1.465e+03]
 [-1.000e+00]
 [-3.330e+02]
 [ 7.100e+01]
 [-2.000e+00]
 [-1.600e+01]
 [-2.000e+00]
 [ 6.000e+00]
 [-2.600e+01]
 [-4.800e+01]
 [-2.100e+01]
 [-4.300e+01]
 [-3.500e+01]
 [-3.501e+03]
 [ 1.201e+03]
 [-5.200e+01]
 [ 2.400e+01]
 [ 2.903e+03]
 [-5.990e+02]
 [ 5.310e+02]
 [-8.400e+01]
 [ 1.579e+03]
 [-8.000e+01]
 [ 1.700e+01]
 [ 6.000e+01]
 [ 3.300e+01]
 [-2.200e+01]
 [ 1.000e+01]
 [-6.000e+00]
 [ 7.030e+02]
 [-3.690e+02]
 [-2.450e+03]
 [ 1.900e+01]
 [ 7.100e+01]
 [-1.079e+03]
 [-3.500e+01]
 [-4.500e+01]
 [ 3.600e+01]
 [-5.600e+01]
 [ 1.000e+01]
 [-3.400e+01]
 [-4.500e+01]
 [ 2.180e+02]
 [ 6.900e+01]
 [ 3.800e+01]
 [ 4.600e+01]
 [-5.800e+01]
 [-6.000e+01]
 [-1.600e+01]
 [-2.900e+01]
 [ 

[[
[[ 3.5000e+01]
 [-5.5000e+01]
 [ 1.3000e+01]
 [ 1.2000e+01]
 [-1.7000e+01]
 [-4.2000e+01]
 [-9.0000e+00]
 [-1.7000e+01]
 [ 1.1000e+01]
 [-4.3000e+01]
 [ 2.0000e+00]
 [-1.3000e+01]
 [-6.2800e+02]
 [ 6.5000e+01]
 [ 5.2000e+01]
 [ 1.2720e+03]
 [-1.0600e+02]
 [-1.0000e+00]
 [-2.7000e+01]
 [-9.3000e+01]
 [ 8.8000e+01]
 [-1.2360e+03]
 [ 1.0860e+03]
 [-2.9000e+01]
 [ 6.6000e+01]
 [-1.0000e+00]
 [ 6.0000e+00]
 [ 3.0000e+01]
 [-4.7000e+01]
 [-4.4000e+01]
 [-1.0000e+00]
 [ 3.0000e+00]
 [-3.3000e+01]
 [ 2.6000e+02]
 [-4.3000e+01]
 [ 5.4000e+01]
 [-2.2000e+01]
 [-2.1000e+01]
 [ 3.3090e+03]
 [-2.9000e+01]
 [-9.8000e+01]
 [-4.9000e+01]
 [ 1.9900e+02]
 [-7.8000e+01]
 [-5.3000e+01]
 [ 5.8000e+02]
 [-3.1000e+01]
 [ 1.4000e+01]
 [ 1.6574e+04]
 [ 5.0000e+01]
 [-4.2000e+01]
 [-2.4200e+02]
 [-5.4000e+01]
 [-2.3000e+01]
 [-4.6900e+02]
 [ 3.4000e+01]
 [ 1.0000e+00]
 [-1.2000e+01]
 [-3.0000e+00]
 [-2.0000e+01]
 [ 2.6000e+01]
 [-1.7800e+02]
 [-4.3000e+01]
 [-8.7000e+01]
 [ 0.0000e+00]
 [-4.4000e+01]
 [ 9.00

[[
[[ 4.0000e+01]
 [-2.6000e+01]
 [-1.0400e+02]
 [ 2.1000e+01]
 [-1.6000e+01]
 [-4.5000e+01]
 [ 1.6100e+02]
 [-5.0000e+01]
 [ 1.6000e+01]
 [ 3.5000e+01]
 [ 0.0000e+00]
 [-2.1000e+01]
 [ 2.5000e+01]
 [-2.9000e+01]
 [-9.0000e+00]
 [ 3.2000e+01]
 [ 1.2000e+01]
 [-4.0000e+00]
 [-8.8000e+01]
 [ 4.6000e+01]
 [ 1.7000e+01]
 [ 7.0600e+02]
 [ 3.4000e+01]
 [-3.4000e+01]
 [-4.2000e+01]
 [-6.6000e+01]
 [-8.0000e+00]
 [ 2.0620e+03]
 [ 1.5330e+03]
 [-5.5400e+02]
 [-2.9000e+01]
 [-4.2220e+03]
 [-1.3120e+03]
 [ 1.9000e+01]
 [ 6.2000e+01]
 [ 7.6600e+02]
 [-2.3000e+01]
 [-2.4000e+01]
 [ 2.7200e+02]
 [-3.5600e+02]
 [ 4.0000e+01]
 [-7.9000e+01]
 [-3.8000e+01]
 [ 1.3000e+01]
 [-6.1000e+01]
 [ 6.2000e+01]
 [-3.2000e+01]
 [-2.2000e+01]
 [ 4.8900e+02]
 [-1.5000e+01]
 [-2.0000e+01]
 [-2.0000e+01]
 [-1.8000e+01]
 [ 1.1000e+01]
 [-4.5000e+01]
 [-8.0000e+01]
 [-4.0200e+02]
 [-1.5400e+02]
 [-5.0000e+00]
 [ 3.8000e+01]
 [-3.6000e+01]
 [ 2.6000e+01]
 [ 1.1440e+03]
 [-1.2000e+01]
 [-1.0100e+02]
 [ 0.0000e+00]
 [-2.60

C:\Users\gilbe\Anaconda3\lib\site-packages\simplejson\encoder.py:291: DeprecationWarning: Interpreting naive datetime as local 2018-05-03 18:35:02.987754. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)
